name: "Run Integration Tests"

on:
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            
            - name: Setup Environment
              run: |
                chmod +x ./scripts/setEnvironment.sh
                ./public/scripts/setEnvironment.sh
              shell: bash

            - name: Install dependencies
              run: npm ci
            
            - name: Run integration tests
              run: npm run test
              
