name: "Run Integration Tests"

on:
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        name: "Build and Test"
        runs-on: ubuntu-latest
        env:
            DB_HOST: ${{secrets.DB_HOST}}
            DB_USER: ${{secrets.DB_USER}}
            DB_PASS: ${{secrets.DB_PASS}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_NAME: ${{secrets.DB_NAME}}

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: ${{secrets.DB_NAME}}
                ports:
                    - 3306:3306

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Set Env Variables
              run: |
                export DB_HOST=${{secrets.DB_HOST}}
                export DB_USER=${{secrets.DB_USER}}
                export DB_PASS=${{secrets.DB_PASS}}
                export DB_PORT=${{secrets.DB_PORT}}
                export DB_NAME=${{secrets.DB_NAME}}
                

            - name: Run integration tests
              run: npm run test

