name: "Run Integration Tests"

on:
    pull_request:
        branches:
            - mainm

jobs:
    build_and_test:
        name: "Build and Test"
        runs-on: ubuntu-latest
        env:
            DB_HOST: ${{secrets.DB_HOST}}
            DB_USER: ${{secrets.TEST_DB_USER}}
            DB_PASS: ${{secrets.DB_PASS}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_NAME: ${{secrets.DB_NAME}}
            SNS_ARN: "some-arn"

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASS}}
                    MYSQL_DATABASE: ${{secrets.DB_NAME}}
                ports:
                    - 3306:3306

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Create Logs folder
              run: mkdir -p logs

            - name: Install dependencies
              run: npm ci

            - name: Run integration tests
              run: npm run test

