name: Packer Validate and Format Check

on:
    pull_request:
        branches:
            - mainm

jobs:
    packer_validate_fmt:
        runs-on: ubuntu-latest
        env:
            region: ${{secrets.region}}
            ssh_username: ${{secrets.ssh_username}}
            instance_type: ${{secrets.instance_type}}
            source_ami: ${{secrets.source_ami}}

            
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Zip repo
              run: zip -r packer/webapp.zip .

            - name: Install Packer
              run: |
                  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                  sudo apt-get update && sudo apt-get install packer
                  packer --version


            - name: Packer init
              run: packer init packer/template.pkr.hcl 

            - name: Format Packer Template
              run: packer fmt -check packer/template.pkr.hcl

            - name: Validate Packer Template
              run: |
                cd packer 
                packer validate -var="region=$region" -var="ssh_username=$ssh_username" -var="instance_type=$instance_type" -var="source_ami=$source_ami" template.pkr.hcl